name: Go Module

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  go-mod:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Check go.mod
      run: |
        go mod download
        go mod verify
        go mod tidy
        if [ -n "$(git status --porcelain)" ]; then
          echo "go.mod or go.sum needs to be updated"
          git diff
          exit 1
        fi

    - name: Check for license issues
      uses: apache/skywalking-eyes@main
      with:
        config: .licenserc.yaml
