name: Release Static Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: linux-amd64
            os: linux
            arch: amd64
            goos: linux
            goarch: amd64
          - name: linux-arm64
            os: linux
            arch: arm64
            goos: linux
            goarch: arm64
          - name: windows-amd64
            os: windows
            arch: amd64
            goos: windows
            goarch: amd64
          - name: darwin-amd64
            os: darwin
            arch: amd64
            goos: darwin
            goarch: amd64
          - name: darwin-arm64
            os: darwin
            arch: arm64
            goos: darwin
            goarch: arm64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Install musl-tools (for Linux builds)
      if: matrix.os == 'linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y musl-tools

    - name: Build static binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: 0
      run: |
        go mod download
        go mod verify
        
        # Use musl for Linux builds to avoid glibc dependency
        if [ "${{ matrix.os }}" = "linux" ]; then
          CC=musl-gcc go build -v -ldflags="-s -w -extldflags=-static" -o patternqc-${{ matrix.os }}-${{ matrix.arch }} patternqc.go
        else
          go build -v -ldflags="-s -w" -o patternqc-${{ matrix.os }}-${{ matrix.arch }} patternqc.go
        fi

    - name: Test binary
      if: matrix.os == 'linux' && matrix.arch == 'amd64'
      run: |
        ./patternqc-${{ matrix.os }}-${{ matrix.arch }} -version
        ./patternqc-${{ matrix.os }}-${{ matrix.arch }} 2>&1 | grep -q "Error: -fq1, -fq2 and -outdir are required" || exit 1

    - name: Check binary compatibility
      if: matrix.os == 'linux' && matrix.arch == 'amd64'
      run: |
        # Check if binary is statically linked
        ldd patternqc-${{ matrix.os }}-${{ matrix.arch }} 2>&1 | grep -q "not a dynamic executable" || echo "Binary is statically linked"
        
        # Check binary size
        ls -lh patternqc-${{ matrix.os }}-${{ matrix.arch }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: patternqc-${{ matrix.os }}-${{ matrix.arch }}
        path: patternqc-${{ matrix.os }}-${{ matrix.arch }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          patternqc-linux-amd64/patternqc-linux-amd64
          patternqc-linux-arm64/patternqc-linux-arm64
          patternqc-windows-amd64/patternqc-windows-amd64
          patternqc-darwin-amd64/patternqc-darwin-amd64
          patternqc-darwin-arm64/patternqc-darwin-arm64
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
